### ISSUE TITLE
Decouple parsing of form fields and URL params

### ISSUE THREAD

**Issue by dukedougal** [falconry/falcon#418] opened 2015-01-24 08:15 UTC
My application receives requests that have a field named "email" in the URL plus receives a field named "email" in the POST form data.  

Same field name, entirely different context, which presents an issue because Falcon integrates the two fields under one key into req.params.  How can I distinguish one from the other?  Might be worth considering Falcon doing it a different way  - form fields and URL params aren't the same thing so perhaps shouldn't be in the same data structure.

Leading on from this problem - I can't find a way to get the form POST data again because another call to req.stream.read() returns nothing and there's no stream.seek(0) to allow me to rewind to the start of the file so there's no way to manually read the form POST data myself.

Setting aside the issue described above, my application needs to forward the POST form fields onto another server anyway so I need to grab only the POST forms fields, so the automatic parsing and integration of fields into req.params means that there is no way for me to identify which fields in req.params came from POST data and which came from URL params.

I'm kinda stuck point in my development cause I can't implement my functionality cause the POST data is gone and req.params isn't usable for my purpose. 

Ideally Falcon would parse the POST form data fields to a separate data structure to req.params, and would also give the ability to get directly to the POST data even if the form data has been parsed.

thanks

**Comment by kgriffs** [comment] 2015-02-09 21:58
@dukedougal I agree that we need to revisit the way Falcon handles form POSTs (see also the last few comments at the bottom of #180), and would like to see what we can get done for the next release (0.3). That release has a lot of issues in it at the moment, but I'll be going through and prioritizing things and moving a lot of the items out to later releases.

I'm going to assign this to 0.3 for now so it isn't overlooked in the triaging process. I'll probably combine this with portions of #180.

**Comment by kgriffs** [comment] 2015-02-09 23:05
P.S. - In the meantime, you might try inheriting from ``falcon.Request`` and overriding ``_parse_form_urlencoded``.

```python
import falcon
from falcon.util import uri


class CustomRequest(falcon.Request):
    __slots__ = ('form_entries')

    def __init__(self, env, options=None):
        self.form_entries = {}
        super(CustomRequest, self).__init__(env, options)

    def _parse_form_urlencoded(self):
        body = self.stream.read()

        # NOTE(kgriffs): According to http://goo.gl/6rlcux the
        # body should be US-ASCII. Enforcing this also helps
        # catch malicious input.
        try:
            body = body.decode('ascii')
        except UnicodeDecodeError:
            body = None
            self.log_error('Non-ASCII characters found in form body '
                           'with Content-Type of '
                           'application/x-www-form-urlencoded. Body '
                           'will be ignored.')

        if body:
            extra_params = uri.parse_query_string(
                uri.decode(body),
                keep_blank_qs_values=self.options.keep_blank_qs_values,
            )

            self.form_entries = extra_params


# Register it like this (requires Falcon 0.2)

api = falcon.API(request_type=CustomRequest)


# Simple functional test
import json
from falcon import testing

headers = {"Content-Type": "application/x-www-form-urlencoded"}
body = 'email=somebody@example.com'
env = testing.create_environ(path='/foo', method='POST', headers=headers,
                             body=body)


class MyResource(object):
    def on_post(self, req, resp):
        doc = {
            'form_entries': req.form_entries,
            'query_params': req.params,
        }

        resp.body = json.dumps(doc, ensure_ascii=False)


api.add_route('/foo', MyResource())
srmock = testing.StartResponseMock()
result = api(env, srmock)

print(result[0].decode('utf-8'))
```

**Comment by kgriffs** [comment] 2015-02-10 19:19
P.S.S. - If you want to parse the request body elsewhere, you could do something similar to the above, but make ``_parse_form_urlencoded`` a noop.

**Comment by kgriffs** [comment] 2015-03-27 17:58
NOTE: The current plan is to create a separate interface for form params vs. query string params. The request body will no longer be automatically consumed, only being parsed the first time a form param method is called. We might also want to expose a method or property for getting the raw request body.

**Comment by kgriffs** [comment] 2015-04-01 21:37
Confirmed: we need to provide access to the raw string as well.

**Comment by lwcolton** [comment] 2015-09-14 22:28
@kgriffs is #493 getting merged or does it still need work?

**Comment by necaris** [comment] 2015-09-14 22:33
I'm still up for taking it on if there's remaining work.

On Mon, Sep 14, 2015 at 6:28 PM, lwcolton <notifications@github.com> wrote:

> @kgriffs <https://github.com/kgriffs> is #493
> <https://github.com/falconry/falcon/pull/493> getting merged or does it
> still need work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/falconry/falcon/issues/418#issuecomment-140223830>.
>



-- 
Rami Chowdhury
"A mind all logic is like a knife all blade - it makes the hand bleed that
uses it." -- Rabindranath Tagore
+1-408-372-6496 / +44-7581-430-517 / +88-0189-245544

**Comment by kgriffs** [comment] 2015-09-24 03:07
@necaris thanks so much for your patience and persistence, and thanks @lwcolton for helping review! PR #493 is next on my list to land. I'll post further comments soon. This is one of the things that I definitely want to get into the 1.0 release.

**Comment by kgriffs** [comment] 2016-02-29 22:31
For 0.4, I'm considering adding an an option to `RequestOptions` to enable/disable parsing form params as currently implemented. It would be disabled by default (breaking change, but easy to work around). Thoughts?

**Comment by kgriffs** [comment] 2016-02-29 22:37
To be clear, this would simply be a short-term measure while we sort out a long-term solution.

**Comment by kgriffs** [comment] 2016-05-25 17:09
FWIW I'm planning a design session during PyCon (sprints or perhaps earlier in the week) to sort this out. Everyone feel free to ping me if you will be there and would like to join in.

**Comment by kgriffs** [comment] 2016-11-23 02:01
OK, for 1.2 I'd like to get this over the finish line. After looking at several different options, here is my proposal.

Implement a new design for accessing parameters, consisting of three additional properties on the Request class:

```py
class Request(object):
    """Represents a client's HTTP request.

    Attributes:
        qs: A ParameterSource instance for retrieving query string parameters.
        form: A ParameterSource instance for retrieving HTML form control
            values. Currently only forms that do not contain file uploads, and
            are submitted with the "application/x-www-form-urlencoded" content
            type, are supported.

            Note:
                When first accessed, the `form` attribute will cause the request
                body stream to be read by the framework. After this occurs, 
                the application should not attempt to access `req.stream`
                directly.
        qs_or_form: A ParameterSource instance for retrieving a parameter that
            may be found in either the query string or in the body of the request
            as an HTML form submission.
    """
```

Note that accessing `form` for the first time triggers a read of the request body stream. It may be prudent for the framework to replace `req.stream` at that point with something that always raises an error when any attempt is made to use it.

The ParameterSource interface is defined as:

```py
class ParameterSource
    def get(self, name, default=None, filter=None, required=False):
        """Get a parameter by name.

        Examples:
            >>> req.qs.get('max', filter=int)
            15
            >>> req.qs.get('detailed', False, bool)
            False

        Note:
            If more than one value is available for the parameter, only one
            of the values will be returned, but it is undefined which one. Use
            `get_list()` to retrieve all the values.

        Args:
            name (str): The name of the parameter to retrieve.

        Keyword Args:
            default: The value to return if the request does not include the
                desired parameter (default ``None``). The default value is not
                passed through the filter.
            filter (callable): A callable that accepts the raw string value of
                the parameter and returns a modified or converted value to be
                used in place of the original.
            required (bool): Set to ``True`` if the parameter is required,
                otherwise ``False`` (default ``False``). If ``True``, and the
                parameter is missing, an instance of ``HTTPInvalidParam`` is
                raised.

        Raises:
            HTTPInvalidParam: The filter raised an error, or the parameter is
                required but not present in the request.
        """

    def get_int(self, name, default=None, min=None, max=None, required=False):
        """Get a parameter and convert it to an int.

        Args:
            name (str): The name of the parameter to retrieve.

        Keyword Args:
            default: The value to return if the request does not include the
                desired parameter (default ``None``).
            min (int): The minimum value, if any, allowed for this
                parameter (default ``None``). If the parameter is less than
                `min`, an instance of ``HTTPInvalidParam`` is raised.
            max (int): The maximum value, if any, allowed for this
                parameter (default ``None``). If the parameter is greater than
                `max`, an instance of ``HTTPInvalidParam`` is raised.
            required (bool): Set to ``True`` if the parameter is required,
                otherwise ``False`` (default ``False``). If ``True``, and the
                parameter is missing, an instance of ``HTTPInvalidParam`` is
                raised.

        Raises:
            HTTPInvalidParam: The parameter can not be converted to an ``int``,
                or the parameter is required but not present in the request.
        """

    def get_bool(self, name, default=None, flag=False, required=False):
        """Get a parameter and convert it to a bool.

        Strings interpreted as ``True``::

            true
            True
            yes
            on
            1

        Strings interpreted as ``False``::

            false
            False
            no
            off
            0

        Args:
            name (str): The name of the parameter to retrieve.

        Keyword Args:
            default: The value to return if the request does not include the
                desired parameter (default ``None``).
            flag (bool): Set to ``True`` to treat the case of the parameter
                name being present in the request, but without a value, as if
                the value had been specified as "true" (default ``False``).
                Otherwise, such parameters will be ignored. To recognize such
                parameters, you must also set
                :py:attr:`~.RequestOptions.keep_blank_qs_values` to
                ``True`` via :any:`API.req_options`.
            required (bool): Set to ``True`` if the parameter is required,
                otherwise ``False`` (default ``False``). If ``True``, and the
                parameter is missing, an instance of ``HTTPInvalidParam`` is
                raised.

        Raises:
            HTTPInvalidParam: The parameter can not be converted to a ``bool``,
                or the parameter is required but not present in the request.
        """

    def get_list(self, name, default=None, minlen=None, maxlen=None, element_filter=None, required=False):
        """Get a parameter and convert it to a list.

        List items must be comma-separated (e.g., "t=1,2,3") or must be provided
        as multiple instances of the same parameter (e.g., "t=1&t=2&t=3"). CSV-
        style parsing may be disabled by setting
        :py:attr:`~.RequestOptions.auto_parse_qs_csv` to ``False``
        via :any:`API.req_options`.

        Args:
            name (str): The name of the parameter to retrieve.

        Keyword Args:
            default: The value to return if the request does not include the
                desired parameter (default ``None``).
            minlen (int): The minimum length, if any, allowed for the list 
                (default ``None``). If the length of the list is less than
                `minlen`, an instance of ``HTTPInvalidParam`` is raised.
            maxlen (int): The maximum length, if any, allowed for the list 
                (default ``None``). If the length of the list is greater than
                `maxlen`, an instance of ``HTTPInvalidParam`` is raised.
            element_filter (callable): A callable that accepts a raw string value 
                representing a single element in the list, and returns a modified 
                or converted value to be used in place of the original.
            required (bool): Set to ``True`` if the parameter is required,
                otherwise ``False`` (default ``False``). If ``True``, and the
                parameter is missing, an instance of ``HTTPInvalidParam`` is
                raised.

        Raises:
            HTTPInvalidParam: The element filter raised an error, or the parameter 
                is required but not present in the request.
        """

    def get_date(name, default=None, format_string='%Y-%m-%d', required=False):
        """Get a parameter and convert it to a datetime.

        List items must be comma-separated (e.g., "t=1,2,3") or must be provided
        as multiple instances of the same parameter (e.g., "t=1&t=2&t=3"). CSV-
        style parsing may be disabled by setting
        :py:attr:`~.RequestOptions.auto_parse_qs_csv` to ``False``
        via :any:`API.req_options`.

        Args:
            name (str): The name of the parameter to retrieve.

        Keyword Args:
            default: The value to return if the request does not include the
                desired parameter (default ``None``).
            format_string (str): String used to parse the param value into a
                datetime (default ``"%Y-%m-%d"``). Any format recognized by 
                `strptime()`` is supported.
            required (bool): Set to ``True`` if the parameter is required,
                otherwise ``False`` (default ``False``). If ``True``, and the
                parameter is missing, an instance of ``HTTPInvalidParam`` is
                raised.

        Raises:
            HTTPInvalidParam: The parameter could not be parsed into a datetime, 
                or is required but not present in the request.
        """
```

Note that falcon.HTTPInvalidParam will need to be modified to allow for setting the original exception and traceback info when a `filter` or `element_filter` raises an error, so that applications can log that information using a custom error handler, if desired.

Example usage:

```py
req.qs.get('id', 23, filter=int)
req.qs.get('detailed', False, bool)
req.qs.get_int('max', 23, min=1, max=10)
req.qs.get_bool('detailed', False, flag=True)

req.form.get_list('coord', minlen=2, maxlen=2, element_filter=int)

req.qs_or_form.get_date('start')
```

Note that the interface for dealing with files uploaded via HTML forms is not specified above. This will be handled by an additional `Request` property (`req.files`) and is detailed in a separate issue (see also #953).

**Comment by lwcolton** [comment] 2016-11-29 21:51
@kgriffs Looks great, super excited to get started helping with this.  Are you pretty firm on the attribute naming, or would you consider calling "qs"  "query" instead?   Also are you planning to have "qs_or_form" and "params" co-exist?   Or could we update params to use ParameterSource instead of adding qs_or_form?   Last question, do you have any issues with ParameterSource supporting dictionary-style access via UserDict and/or __getitem__?

**Comment by lwcolton** [comment] 2016-11-29 22:03
@necaris Are you wanting to contribute ParamterSource and the additional items here?  Since you originally had a PR open for this issue just let me know what all you want to do

**Comment by kgriffs** [comment] 2017-01-26 21:10
@lwcolton thanks for taking this!

> Are you pretty firm on the attribute naming, or would you consider calling "qs" "query" instead?

I'm open to other names, so "query" would be fine.

> Also are you planning to have "qs_or_form" and "params" co-exist? Or could we update params to use ParameterSource instead of adding qs_or_form? 

My main concern is backwards-compatibility. We can have `params` return something that is `dict`-like, but there's always the chance that we miss some edge-case behavior of a `dict` that breaks someone. It would probably be safer to convert `ParameterSource` to a `dict` (and memoize the result) that is then returned when someone calls `params`. We can let people know that they should switch to `query_or_form` and that `params` will be removed in a future release (probably 2.0).

Alternatively, we can just rev Falcon to 2.0 when this patch is ready to go, and that would let us repurpose `params` in lieu of introducing `query_or_form`.

> do you have any issues with ParameterSource supporting dictionary-style access via UserDict and/or `__getitem__`? 

I think that's a good idea. The only question is what error to raise when the key is not found. We may want to define an error that inherits from both `KeyError` and `HTTPBadRequest`.

**Comment by kgriffs** [comment] 2017-04-25 17:14
Moving to Falcon 2.0 to allow us to make breaking changes.

**Comment by lwcolton** [comment] 2017-04-25 17:41
Cool, sorry for the lack of activity I was working on some Node.js stuff
for a couple months but I am back on Python now at a shop that uses falcon
so still looking to contribute here

**Comment by branelmoro** [comment] 2018-03-18 06:09
I have added changes in request.py in falcon framework to parse application/x-www-form-urlencoded and multipart/from-data.
I have raised pull request - https://github.com/falconry/falcon/pull/1233 it is not yet merged in master.
Check this - https://github.com/branelmoro/falcon
I hope this will help access POST and GET parameters separately and we will be able to upload files as well.
Good thing about the change is that it will not load entire uploaded file in memory.

**Comment by vytas7** [comment] 2019-11-04 19:55
Although some comments are straying into the territory of `multipart/from-data`, I am primarily reading this issue as concerning decoupling `application/x-www-form-urlencoded` from `req.params`.

As such, the issue has been addressed in https://github.com/falconry/falcon/pull/1537 by allowing to access the submitted URL-encoded form as `req.media`.

Furthermore, `auto_parse_form_urlencoded` is no longer enabled by default. And it would be marked as deprecated as part of https://github.com/falconry/falcon/issues/1580.

I'm closing this issue as it seems to be superseded and/or duplicated by other issues already in progress (and FWIW with open PRs).

**Closed by vytas7** 2019-11-04 19:55 UTC
Labels: breaking-change, enhancement, in progress
