### ISSUE TITLE
I found out in falcon that admin access is difficult to do and also graphical databases like neo4j cannot do and  have not source.

### ISSUE THREAD

**Issue by MajidHeydari** [falconry/falcon#1878] opened 2021-03-07 11:21 UTC
I found out in falcon that admin access is difficult to do and also graphical databases like neo4j cannot do and  have not source.

**Comment by CaselIT** [comment] 2021-03-07 13:03
Hi, I'm not sure I understand what is the request here, could you clarify?

**Comment by MajidHeydari** [comment] 2021-03-07 14:58
I want to connect to a graph database like neo4j. How do I do this?

**Comment by vytas7** [comment] 2021-03-07 15:01
"Graphic" databases like neo4j is a duplicate of https://github.com/falconry/falcon/issues/1863.

As for other points raised in the issue's title:
* "Admin access is difficult to do" -- do you mean some kind of interface along the lines of the [Django Admin](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/)?
* "And have not source" -- :confused: please clarify.

**Comment by MajidHeydari** [comment] 2021-03-07 15:08
yes,exist panel in django admin and fastapi but in falcon is not

**Comment by vytas7** [comment] 2021-03-07 15:16
Right... as explained on https://github.com/falconry/falcon/discussions/1864, Falcon does not, itself, ship any ORM inside the framework (in fact, Falcon has no hard dependency on any 3rd party package).
See also our FAQ: [Why doesn’t Falcon come with batteries included?](https://falcon.readthedocs.io/en/latest/user/faq.html#why-doesn-t-falcon-come-with-batteries-included)

Furthermore, Falcon is focused on APIs and back-end services, not on back-end rendered pages like Django. AFAICT FastAPI does not ship a database admin either, although 3rd party community add-ons may exist for that purpose.

This is the route Falcon takes as well -- we maintain a solid core, and let the community innovate specialized add-ons such as database administration.

**Comment by vytas7** [comment] 2021-03-07 15:19
Could you clarify the last part of your comment "and have not source"? :confused:

**Comment by MajidHeydari** [comment] 2021-03-07 15:22
Would it be much easier to learn if falcon had a guide with an example?

**Comment by vytas7** [comment] 2021-03-07 15:30
Falcon does have a [User Guide](https://falcon.readthedocs.io/en/stable/user/index.html), including [quickstart](https://falcon.readthedocs.io/en/stable/user/quickstart.html) and a [longer tutorial](https://falcon.readthedocs.io/en/stable/user/tutorial.html).

The [unstable version of the guide](https://falcon.readthedocs.io/en/latest/user/index.html) (in b2 at the time of writing this) has tutorials both for WSGI, and [ASGI](https://falcon.readthedocs.io/en/latest/user/tutorial-asgi.html) (requires the upcoming Falcon 3.0).

If you find anything specific missing or incorrect in those user guides, it is better to file a documentation issues against these.

**Comment by vytas7** [comment] 2021-03-07 17:17
I'm going to close this issue since it spans a very broad range of subjects.
It's better to file specific bugs and suggestions for improvement, or why not start a [new discussion](https://github.com/falconry/falcon/discussions)?

You're also welcome to join our [Gitter channels](https://falconframework.org/#sectionCommunity) for chat :wave: 

To reiterate, when it comes to docs, we strive hard after having useful and comprehensive documentation; however we're aware that there's room for improvement: https://github.com/falconry/falcon/issues/1393.

**Closed by vytas7** 2021-03-07 17:17 UTC
Labels: needs-information, question
