### ISSUE TITLE
Improve set_cookie() documentation (and validation?) wrt domain name

### ISSUE THREAD

**Issue by sevazhidkov** [falconry/falcon#947] opened 2016-11-12 22:02 UTC
Hi! 

My code is like:
```
        resp.status = '301 Moved Permanently'
        resp.set_header('Set-Cookie', 'user=abc') # With set_cookie result is same
        resp.set_header('Location', '...')
        print(resp._headers)
```

```resp._headers``` shows cookie header, but when I make request, there is no cookie. Is it known problem?

I'm using Python 3.5 and last pip version of falcon

**Comment by sevazhidkov** [comment] 2016-11-12 22:06
Such functionality was earlier implemented on Flask and I didn't had such problem.

**Comment by kgriffs** [comment] 2016-11-14 17:54
Hi @sevazhidkov, This could be due to [the secure attribute](http://falcon.readthedocs.io/en/latest/api/cookies.html#the-secure-attribute). I know that setting this to `False` during development is tedious; one solution may be to introduce an application-wide option to the framework for setting this so it doesn't have to be done for each call to `set_cookie()`.

**Comment by sevazhidkov** [comment] 2016-11-16 11:29
@kgriffs Even with secure=False it still don't work.
I want to note, that host domain and redirection domain is different (it's oAuth authorization)

**Comment by jmvrbanac** [comment] 2017-01-27 03:19
@sevazhidkov Is this still an issue for you? I’m having difficulty replicating the issue you’ve described. For me, the `set-cookie` header is coming through on both the cli and in Chrome. It makes me wonder if this is no longer an issue or there is another service between Falcon and your client that is stripping out the header. If you're still experiencing this behavior, could you provide more information regarding the environment Falcon is running in? 

For clarity sake, here is what I used when I attempted to replicate the issue:
* Python 3.5.2
* Gunicorn 19.6.0
* Falcon 1.1.0
* Httpie 0.9.4 (To make the requests)

Sample App `app.py`
```
import falcon
import json

class QuoteResource:
    def on_get(self, req, resp):
        """Handles GET requests"""
        resp.body = "{}"
        resp.status = '301 Moved Permanently'
        resp.set_header('Set-Cookie', 'user=abc')
        resp.set_header('Location', '...')
        print(resp._headers)

api = falcon.API()
api.add_route('/quote', QuoteResource())
```
Console Return:
```
(falcon-sample) $ gunicorn app:api
[2017-01-26 21:01:28 -0600] [20239] [INFO] Starting gunicorn 19.6.0
[2017-01-26 21:01:28 -0600] [20239] [INFO] Listening at: http://127.0.0.1:8000 (20239)
[2017-01-26 21:01:28 -0600] [20239] [INFO] Using worker: sync
[2017-01-26 21:01:28 -0600] [20242] [INFO] Booting worker with pid: 20242
{'set-cookie': 'user=abc', 'location': '…'}
```

Request:
```
(falcon-sample) $ http -v localhost:8000/quote
GET /quote HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8000
User-Agent: HTTPie/0.9.4



HTTP/1.1 301 Moved Permanently
Connection: close
Date: Fri, 27 Jan 2017 03:01:29 GMT
Server: gunicorn/19.6.0
content-length: 2
content-type: application/json; charset=UTF-8
location: ...
set-cookie: user=abc

{}
```

**Comment by jmvrbanac** [comment] 2017-05-09 00:54
Closing this issue for now. Please re-open this issue if you run into any issues. Thanks!

**Comment by shehzi-khan** [comment] 2018-09-19 04:53
I'm trying to develop a user management interface for my project using the following:

- Python 2.7
- falcon 1.4.1
- falcon-cors 1.1.7
- gunicorn 19.9.0

I'm testing the login page in Google Chrome initiated by ```run``` command in Pycharm Professional.

```
import falcon
from falcon_cors import CORS
cors = CORS(allow_all_origins=True,allow_all_headers=True,allow_all_methods=True)

class User:
    def __init__(self):
        self.name = 'Users API'

    def on_post(self, req, resp):
        try:
            data = urlparse.parse_qs(req.stream.read())
            if "loginEmail" in data.keys() and "loginPassword" in data.keys():
                email = data['loginEmail'][0]
                password = data['loginPassword'][0]
                result = self.authenticate(email, password)
                if result["status"]=="Success":
                    resp.set_cookie('session', result["session"],path="/",domain="192.168.32.17:5000",secure=False)
            else:
                raise Exception, "Email or Password not provided"

            if len(result) <= 0:
                raise Exception, 'Empty Response'
            resp.body = json.dumps(result)

        except Exception as e:
            resp.body = json.dumps({'status': 'Error', 'message': e.message, 'details': str(e)})

    def on_get(self, req, resp):
        try:
            data = req.params
            cookies = req.cookies
            if "session" in cookies.keys():
                session = cookies['session']
                result=self.get(session,data)
                if len(result) <= 0:
                    raise Exception, 'Empty Response'
            else:
                raise Exception, "Session Terminated"

            resp.body = json.dumps(result)
        except Exception as e:
            resp.body = json.dumps({'status': 'Error','message': e.message,'details': str(e)})

api = falcon.API(middleware=[cors.middleware])
api.add_route('/user', User())
```

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body onload="refresh()">
<form method="post" action="http://192.168.32.17:5000/user" accept-charset="UTF-8" id="login-nav">
    <input type="email" name="loginEmail" placeholder="Email address" required>
    <input type="password" name="loginPassword" placeholder="Password" required>
    <button type="submit" id="btnLogin">Sign in</button>
 </form>
<script>
    $(document).ready(function() {
        $('#login-nav').submit(function(){
            $.post($(this).attr('action'), $(this).serialize(), function(json) {
                refresh()
            }, 'json');
            return false;
       });
    });

   function refresh(){
            $.get("http://192.168.32.17:5000/user",  { 'fields': [ "name", "dp" ] }, function(json) {
                if (json["status"]=="Error"){
                    alert(json["message"])
                }
               else {
                $('#dd-username').text(json["data"]["name"])
                $("#dd-photo").attr("src",json["data"]["dp"])
                }
            }, 'json');
    }

    function getCookie(cname) {
        var name = cname + "=";
        var decodedCookie = decodeURIComponent(document.cookie);
        var ca = decodedCookie.split(';');
        for(var i = 0; i <ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    function checkCookie() {
        var session = getCookie("session");
        if (session ==null || session==""){
            return false
        }
        else{
            return true
        }
</script>
</body>
</html>
```
On login request I'm getting required response as given below:
```{"status": "Success", "message": "Session has been created successfully", "session": "F26F75C27942DE27"}```

But on ```refresh()```, I'm getting following response:
```{"status": "Error", "message": "Session Terminated"}```

I also tried checking for cookie using ```chechCookie()``` method above and it returns false as well.

**Comment by vytas7** [comment] 2018-12-28 19:47
(will do a short investigation on this one :microscope: )

**Comment by vytas7** [comment] 2018-12-28 20:17
@shehzi-khan I can indeed reproduce your problem using the provided test case (I took the liberty to edit it a bit and fill in the missing methods -- **warning** -- my examples are solely for illustration purposes and do not represent sound web development practices). However, this is caused a bug in this test case, not by a bug in the framework itself: cookies are set on domains only, not ports. Upon changing that, the test case starts functioning as expected:

```python
import hashlib
import os
import random
import urlparse

import falcon
from falcon_cors import CORS

cors = CORS(allow_all_origins=True,
            allow_all_headers=True,
            allow_all_methods=True)

HOST = '192.168.32.17'
PORT = 5000

USER_LANGUAGES = ('C', 'C++', 'Golang', 'PHP', 'Python', 'Ruby', 'Rust')


class User(object):
    def __init__(self):
        self.name = 'Users API'
        self.data = {}

    def get(self, session, data=None):
        return self.data[session]

    def authenticate(self, email, password):
        success = email.strip() and password.strip()
        result = {'status': 'Success'} if success else {'status': 'Failure'}
        if success:
            session = hashlib.md5(password).hexdigest()
            result.update(session=session)
            language = random.choice(USER_LANGUAGES)
            if language == 'PHP':
                # Just no, please
                raise falcon.HTTPForbidden
            self.data[session] = {'language': language}

        return result

    def on_post(self, req, resp):
        try:
            data = urlparse.parse_qs(req.stream.read())
            if "loginEmail" in data.keys() and "loginPassword" in data.keys():
                email = data['loginEmail'][0]
                password = data['loginPassword'][0]
                result = self.authenticate(email, password)
                if result["status"] == "Success":
                    resp.set_cookie('session', result["session"],
                                    path="/",
                                    # see RFC 6265, section-8.5:
                                    # Cookies do not provide isolation by port
                                    # domain="{}:{}".format(HOST, PORT),
                                    domain=HOST,
                                    secure=False)
            else:
                raise Exception('Email or Password not provided')

            if len(result) <= 0:
                raise Exception('Empty Response')
            resp.media = result

        except falcon.HTTPForbidden:
            raise

        except Exception as e:
            raise falcon.HTTPBadRequest(title='Error', description=str(e))

    def on_get(self, req, resp):
        try:
            data = req.params
            cookies = req.cookies
            if "session" in cookies.keys():
                session = cookies['session']
                result = self.get(session, data)
                if len(result) <= 0:
                    raise Exception('Empty Response')
            else:
                raise Exception("Session Terminated")

            resp.media = result

        except Exception as e:
            raise falcon.HTTPBadRequest(title='Error', description=str(e))


api = falcon.API(middleware=[cors.middleware])
api.add_route('/user', User())
api.add_static_route('/app', os.path.dirname(__file__))
```

**Comment by graemedouglas** [comment] 2019-07-23 19:39
I too am having issues getting `set_cookies` to work.

Here is my very simple code:

```
import falcon

class HelloResource(object):
    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200
        resp.body = 'Hello World!'

class UserAuthenticationResource(object):
    def on_post(self, request: falcon.Request, response: falcon.Response):
        response.set_cookie('user', 'aaaaaa', secure=False)

app = falcon.API()

app.add_route('/', HelloResource())
app.add_route('/login', UserAuthenticationResource())
```

It's run with gunicorn: `gunicorn --bind 0.0.0.0:8888 path.to.file:app`.

I've done a lot of experimentation with `set_cookie` parameters and binding to `localhost` etc. yet nothing has worked. Using falcon 2.0.0 and gunicorn 19.9.0

**Comment by graemedouglas** [comment] 2019-07-26 16:55
Well this is very derpy/embarrassing. Last few frameworks I used didn't set `http_only` to `True` by default, and this one does. I just misread the Chrome cookie inspector the first few times before I realized my mistake. Sorry for the trouble.  🤦‍♂

**Comment by atMari** [comment] 2019-09-09 08:35
I was having the same issue @graemedouglas.  Thanks for writing this, as it helped me resolve it.

**Closed** 2020-09-08 06:39 UTC
Labels: documentation, good first issue, needs contributor
