### ISSUE TITLE
Why falcon did not make response more easy ?

### ISSUE THREAD

**Issue by kevin-leptons** [falconry/falcon#922] opened 2016-09-30 18:53 UTC
falcon use two way to create response

**Way 1: use res.body**

``` python
class Resource(object):
    def on_get(self, req, res):
        res.body = json.dump({'id': 123, 'name': 'work in office'})
```

**Way 2: use req.context**

``` python
class Resource(object):
    def on_get(self, req, res):
        req.context['res'] = {'id': 123, 'name': 'work in office'}

# And add middleware to convert req.context['res'] and put result to res.body
```

Why falcon did not make response more easy  by that way

``` python
class Resource(object):
    def on_get(self, req, res):
        return {'id': 123, 'name': 'work in office'}

# And falcon will convert returned value and put result to res.body
```

**Comment by karmux** [comment] 2016-10-24 08:10
I like the current consistent behaviour when response body has to be always string created by developer. In this way you are free to select your serializing tools (std json, marshmallow, dicttoxml etc). Letting Falcon to automatically serialize objects would be too much magic under the hood and this usually means also less flexibility in my opinion.

**return** would be nice to have though.

**Comment by AndreiRegiani** [comment] 2016-11-21 10:44
@kevin-leptons Take a look at [falcon-jsonify](https://github.com/AndreiRegiani/falcon-jsonify), it's a middleware I just released to help with JSON requests and responses.

```python
class Resource(object):
    def on_get(self, req, res):
        res.json = {'id': 123, 'name': 'work in office'}
```

```python
    def on_post(self, req, res):
        name = req.json['name']

        # or use helper function which raises 500 Bad Request if field not provided
        name = req.get_json('name')

        # built-in validations
        name = req.get_json('name', min=1, max=16, default="Anonymous")
```

**Comment by kevin-leptons** [comment] 2016-11-21 13:27
@AndreiRegiani, I have viewed falcon-jsonify. I have idea to make it better: remove validators and let jsonschema do it. You must do one thing and do it as well: convert json data from request and to response

You it make sense

**Comment by AndreiRegiani** [comment] 2016-11-25 21:43
@kevin-leptons I will take a look and consider `jsonschema`, thanks for the suggestion. If you have any other thoughts create an issue on [falcon-jsonify](https://github.com/AndreiRegiani/falcon-jsonify), it's a work in progress really, right now I'll push to pip compatibility to Python 3 and add some more improvements.

**Comment by kornicameister** [comment] 2017-02-23 07:08
how does it go with 

> If ujson is installed it will be used in lieu of json to speed up error serialization and query string parsing under CPython. PyPy users should continue to use json.

taken from [here](http://falcon.readthedocs.io/en/latest/changes/1.2.0.html)

**Comment by jmvrbanac** [comment] 2017-05-21 00:13
This is kinda a duplicate of #145. As a result, I'm going to go ahead and close this issue. On the positive side, we're in the process of making this easier in this PR: #1050 .

**Closed by jmvrbanac** 2017-05-21 00:13 UTC
