### ISSUE TITLE
Cannot handle UTF-8 route

### ISSUE THREAD

**Issue by hhschu** [falconry/falcon#1004] opened 2017-03-01 08:24 UTC
When UTF-8 characters present in the route, either as part of a static URL or as a variable, Falcon has trouble handling requests.

In the case of static URL, for example `app.add_route('/foo/bar/測試', SomeResource())`, I get a 404 error when requesting this URL.

If I have a route `app.add_route('/foo/bar/{something}', SomeResource())` like this, sometimes I get a 400 and a message of _Invalid HTTP Version_.

However, GET parameters work well with UTF-8.

**Comment by kgriffs** [comment] 2017-04-25 18:54
Hi @hhschu, to help me reproduce this, can you let me know what WSGI server and Python version you used in your tests? Also, when requesting the URL are you percent-encoding it first per the HTTP/1.1 specification?

**Comment by hhschu** [comment] 2017-04-25 19:07
Python version: 3.6
WSGI by gunicorn version 19.6.0

And no, I later found out that I did not percent encoding my UTF-8 string first. After percent encoding, this works smoothly. Sorry for the trouble.

**Comment by vytas7** [comment] 2018-12-28 20:33
@hhschu great that you found out the root cause.
We are thereby closing this issue, but do not hesitate to report any other problems you encounter using Falcon framework!

**Closed by vytas7** 2018-12-28 20:33 UTC
Labels: bug, needs-information
