### ISSUE TITLE
pylint fails on use of constants in falcon 2.0.0

### ISSUE THREAD

**Issue by uriva** [falconry/falcon#1553] opened 2019-06-05 23:23 UTC
Running pylint on a file that imports falcon and uses various constants fails.

> server.py:67:28: E1101: Module 'falcon' has no 'MEDIA_JSON' member (no-member)
> server.py:68:22: E1101: Module 'falcon' has no 'HTTP_200' member (no-member)
> server.py:85:28: E1101: Module 'falcon' has no 'MEDIA_JSON' member (no-member)
> server.py:86:22: E1101: Module 'falcon' has no 'HTTP_200' member (no-member)
> server.py:103:28: E1101: Module 'falcon' has no 'MEDIA_JSON' member (no-member)
> server.py:104:22: E1101: Module 'falcon' has no 'HTTP_200' member (no-member)
> server.py:110:28: E1101: Module 'falcon' has no 'MEDIA_JSON' member (no-member)
> server.py:111:22: E1101: Module 'falcon' has no 'HTTP_200' member (no-member)
> server.py:119:22: E1101: Module 'falcon' has no 'HTTP_200' member (no-member)
> server.py:127:22: E1101: Module 'falcon' has no 'HTTP_200' member (no-member)
> server.py:134:22: E1101: Module 'falcon' has no 'HTTP_200' member (no-member)

Example handler:
```
import falcon

...

class Handler:
    def on_get(self, req, resp):
        resp.body = "asd"
        resp.content_type = falcon.MEDIA_JSON
        resp.status = falcon.HTTP_200  # pylint fails on this line.

...
```

However it doesn't fail for stuff like `falcon.API`.

Any ideas?

**Comment by vytas7** [comment] 2019-06-06 09:38
Hi @uriva !
`pylint`, particularly with its default settings, can be perceived as extremely picky and opinionated. Probably that has contributed to the rise of `flake8` (==`pep8` + `pyflakes`) popularity.

OTOH, I think I can see what `pylint` means in this particular case. We should probably define a proper `__all__` specifier for the `falcon` module, that specifies all the public constants and functions hoisted into the `falcon` namespace.

**Comment by uriva** [comment] 2019-06-06 17:40
I couldn't agree more about pylint and its maintainers...

**Comment by Hanaasagi** [comment] 2019-08-27 09:41
Hello, I think pylint could recognize the `from falcon.status_codes import *` if we import from a Python source file instead of shared library. And I find that if we install the falcon from pypi, it will get some `.so` file which was compiled by cython.

Run following command

```Bash
find `pip show falcon | grep Location | awk '{print $2}'`/falcon -name "*.so"
```

will get 
```
/root/py37/lib/python3.7/site-packages/falcon/responders.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/response.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/status_codes.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/api_helpers.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/media/handlers.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/media/msgpack.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/media/base.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/media/json.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/vendor/mimeparse/mimeparse.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/request.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/response_helpers.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/http_status.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/errors.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/uri.cpython-37m-x86_64-linux-gnu.so
/root/py37/lib/python3.7/site-packages/falcon/api.cpython-37m-x86_64-linux-gnu.so
```

If remove those file, pylint will not complain E1101. 

The manylinux whl in pypi is already include those file. So a workaround is installed the source
```Bash
pip uninstall falcon
pip install no-manylinux falcon
```

**Comment by ckanesan** [comment] 2019-10-23 06:10
FYI, another workaround is to add `falcon` to the `extension-pkg-whitelist` configuration parameter to pylint. The `no-manylinux` package instructs pip to ignore any manylinux binaries and is a bit overkill in some cases.

**Comment by rphes** [comment] 2020-06-02 10:36
I have also run into this issue when using http errors. Specifically, `HTTPNotFound` using either `from falcon import HTTPNotFound` or `from falcon.errors import HTTPNotFound`. The cause is likely the same as above, so maybe the title should be changed to something more general to reflect that.

Additionally, I've tested this on macOS Mojave and it is not an issue there. This might be obvious to those with more knowledge of wheels, but I wanted to point it out regardless.

**Comment by abid1998** [comment] 2021-06-28 18:28
Hello if any help is required on this i can take it up. Can anyone tell me which way should i do it?

**Comment by vytas7** [comment] 2021-06-28 18:50
Hi @abid1998 !
It is unclear, IIRC @CaselIT made some changes that might have partially fixed the issue.
Or, maybe the problem was completely different than I was speculating :thinking: 

Could you install `pylint` and try digging into this?

**Comment by abid1998** [comment] 2021-06-28 18:50
Yup on it.

**Comment by CaselIT** [comment] 2021-06-28 19:08
The issue should still be present because we use `from foo import *`

Specifically in the file where we list all the http statuses we don't define an `__all__` since that would be impractical (ie be longer than the entire file). Maybe we could programmatically generate one, but I'm not sure if it would work

**Comment by vytas7** [comment] 2022-02-20 19:39
I've just verified this again, and it does seem that the analysis by @Hanaasagi, @ckanesan and others is correct: `pylint` is unable to properly dig into binary modules, particularly when used in conjunction with star imports etc.

It is unlikely that we'll want to do the impractical and go to great lengths just to satisfy `pylint`; our resources are probably better spent on adding typing support etc. Closing this for now; we can reopen if we _really_ reconsider.

**Closed by vytas7** 2022-02-20 19:39 UTC
Labels: cleanup, needs contributor, maintenance
