### ISSUE TITLE
Add Response.expires to set the Expires header to a datetime instance

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1210] opened 2018-01-18 21:02 UTC

**Comment by MichaelYusko** [comment] 2018-01-28 21:54
@kgriffs Hello, I'm happy to solve the issue, but could you provide a little bit more details?

Thank you.

**Comment by alysivji** [comment] 2018-08-04 16:45
Started to look into this, but looks like it has already been completed.

This issue is a duplicate of https://github.com/falconry/falcon/issues/1268 which was resolved by https://github.com/falconry/falcon/pull/1298

**Comment by kgriffs** [comment] 2019-05-05 23:32
[closes]

**Comment by vytas7** [comment] 2021-02-21 16:43
(Looks like we simply forgot to close this.)

**Closed by vytas7** 2021-02-21 16:43 UTC
Labels: enhancement, good first issue, needs contributor
