### ISSUE TITLE
testing.Result.json breaking change in 1.4

### ISSUE THREAD

**Issue by bitdivision** [falconry/falcon#1205] opened 2018-01-16 10:50 UTC
I feel like the change to result.json in 1.4 should have been flagged up in changelog.
```
- ``testing.Result.json`` now returns None when the response body is
  empty, rather than raising an error.
```

The above was listed in the changelog under new and improved however changing a method to return None rather than raising an exception is a breaking API change.

This broke some code we were using:

```
try:
     returned = result.json
except json.decoder.JSONDecodeError:
￼     returned = {}
```

This is the second time a minor API has caught us out: https://github.com/falconry/falcon/blob/ef72b31196a692bcb186277efb8d4446fd56073e/falcon/api.py was released in 1.1 I believe.

**Comment by kgriffs** [comment] 2018-01-16 16:31
@bitdivision Thanks for the feedback. This should have indeed been considered a breaking change and postponed to 2.0. We'll walk this back and put out a 1.4.1 shortly. Please let me know if you run into any other issues.

**Comment by kgriffs** [comment] 2018-01-16 19:00
[Fixed in 1.4.1]

**Closed by kgriffs** 2018-01-16 19:00 UTC
Labels: bug

**Comment by bitdivision** [comment] 2018-01-16 19:49
Thanks @kgriffs 

And thank you for all your hard work on falcon. It's a really cool framework!

**Comment by tribals** [comment] 2018-12-19 14:42
The parsing of request body is not so simple as it looks at first glance. For example, HTTP [spec says](https://stackoverflow.com/a/983458/4835578) that `GET` request _can_ have body, but it _shouldn't have any meaning_ (to the server).

Of what I'm definitely sure is that _accessing `req.media` shouldn't result in any exception raised_, be it empty or not. [1]

(I placed this statement on separate line intentionally)

Why so? Think of middlewares. When you are writing resource, you are crystal-clear assured which HTTP verb exactly you are processing - you implement different methods for each one - `on_get`, `on_post` and so on. You may write a lot of simple resources which responds to only `GET` method and not encounter this kind of problem. But you will be very surprised when you are going to implement your first middleware that deals with request body in some way, because middleware processes _every request_, be it `GET`, `POST` or any other HTTP verb. We are, in our company, using _a lot_ of middlewares.

Personally I prefer to return `None` for empty request body. It is not comply to all demands, but think of it again: when request body is empty, you should return _something_ (if we agree with statement [1]), or, in other words, you should return _nothing_. And, in Python, _nothing_ is, simlpy, `None`.

The root cause of problem, I think, is that we need a way to distinguish whether the body was _actually empty_ or media handler just failed to parse it. By now we can't do that because of of missing interface of media handlers and ugly interfaces of parsers. For example, `json` doesn't distinguish between empty and malformed input:

```
>>> import json
>>> json.loads('')
Traceback (most recent call last):
< ...omitted... >
ValueError: No JSON object could be decoded
>>> json.loads('/')
Traceback (most recent call last):
< ...omitted... >
ValueError: No JSON object could be decoded
```

But this can be achieved by wrapping parsing errors into specialized exceptions. Also, I think that raising `HTTPError` (which causes the immediate response) is not responsibility of media handler. This leads to hard-to-debug problems, if you don't know how `req.media` works under the hood.

Here is the example:

```
class MediaHandlerError(Exception): pass
class EmptyBodyError(MediaHandlerError): pass
class RequestBodyParsingError(MediaHandlerError): pass


class JsonMediaHandler(BaseHandler):
    def deserialize(self, raw):
        if raw == '':
            raise EmptyBodyError
        try:
            return json.loads(raw)
        except ValueError as e:
            raise RequestBodyParsingError(raw) from e
```

And `Request`:

```
_unserialized = object()  # sentinel


class Request(falcon.Request):
    def __init__(self, env, options=None):
        super().__init__(env, options)

        self._media = _unserialized

    @property
    def media(self):
        if self._media is _unserialized:
            handler = self.options.media_handlers.find_by_media_type(
                self.content_type, self.options.default_media_type
            )
            try:
                self._media = handler.deserialize(self.bounded_stream.read())
            except EmptyBodyError:
                self._media = None

        return self._media
```

And somewhere in default error handler:

```
    try:
        # calling responder
    except RequestBodyParsingError as e:
        raise falcon.HTTPBadRequest(
            'Invalid JSON', 'Could not parse JSON body - {0}'.format(e)
        )
```

This way we give a developer full control of how things goes: if he/she want to catch errors of parsing request body, he can do so. If not - well, default handler will return `400 Bad Request`. If we catch parsing errors in, for example, `Request.media` property, we divest a programmer of such ability - he should catch `HTTError`s, which is ugly. What is it to `HTTPError` in request body parsing? Nothing. What if a developer want to respond with different HTTP code? Catch `HTTPError`. Ugly.
