### ISSUE TITLE
Delimeter and Request.get_param

### ISSUE THREAD

**Issue by weldpua2008** [falconry/falcon#457] opened 2015-02-23 10:59 UTC
Hi,

I used falcon 0.1.10 and I requested http://localhost?services=ssh,cron and recived:
req.get_param('services'): ssh,cron

```python
 services=req.get_param('services')
 logging.critical( "req.get_param('services'): %s" % req.get_param('services'))

 if services!=None:
     list_of_services=services.split(",")
```
at the end I received list of services. 

When I updated to falcon 0.2.0

I received only one element of param services.
I requested http://localhost?services=ssh,cron and recived:
 CRITICAL [2015-02-23 12:47:44,567] req.get_param('services'): cron

I requested http://localhost?services=ssh;cron and recived:
CRITICAL [2015-02-23 12:54:28,384] req.get_param('services'): ssh;cron

As I understand from: 
http://tools.ietf.org/html/rfc3986#section-2.2
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="

Regards

**Comment by EpicDavi** [comment] 2015-02-27 15:33
I am having similar problems. Will update soon.

**Comment by kgriffs** [comment] 2016-05-10 21:33
Closing the loop on this. The behavior is by design and unifies behavior for `val=1,2` and `val=1&val=2`.

>  Similar to the way multiple keys in form data is handled, if a query parameter is assigned a comma-separated list of values (e.g., 'foo=a,b,c'), only one of those values will be returned, and it is undefined which one. Use `req.get_param_as_list()` to retrieve all the values.

**Closed by kgriffs** 2016-05-10 21:33 UTC
Labels: question
