### ISSUE TITLE
Implement support for specifying query string params in URI templates

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1508] opened 2019-05-06 13:10 UTC
When adding a route, support the inclusion of query string params in the template string. We can take inspiration from RFC 6570 but we'll also want to support filters/validators. Parsed values for the params could either be passed via keyword arguments to responders (that default to ``None``) or be made accessible via the ``Request`` object (TBD).

**Comment by mikeylight** [comment] 2019-05-11 11:51
@kgriffs I'm happy to pick up this ticket.

**Comment by bonicim** [comment] 2021-06-22 01:01
I would appreciate this support. I currently am using Falcon to create a REST API that requires a route to have query string params. 

For example, I want to create a route: ```/my_resource?arg1={arg1}``` and then call it like so: ```curl localhost:8000/my_resource?arg1=foobar```

Looks like this issue has been brought up in the past in #79  and #838

**Comment by vytas7** [comment] 2021-06-22 06:16
Hi @bonicim !
Unless you object I'm going to close this issue as a duplicate of https://github.com/falconry/falcon/issues/838, it seems they are identical.

We also have an umbrella discussion for routing improvements: https://github.com/falconry/falcon/discussions/1818

**Closed by vytas7** 2021-06-22 06:16 UTC
Labels: enhancement, needs contributor

**Comment by CaselIT** [comment] 2021-06-22 06:19
You can use [`get_param`](https://falcon.readthedocs.io/en/stable/api/request_and_response_wsgi.html#falcon.Request.get_param) to get a parameter from a route. There are also some `get_parqm` utility methods to convert the param to different types, like `get_param_as_bool`.

I think this issue is to route to different resources based on a query parameter

**Comment by bonicim** [comment] 2021-06-22 14:23
> Hi @bonicim !
> Unless you object I'm going to close this issue as a duplicate of #838, it seems they are identical.
> 
> We also have an umbrella discussion for routing improvements: #1818

No objection. Feel free to close it.

**Comment by bonicim** [comment] 2021-06-22 14:40
> get_param

Thanks, @CaselIT, for the clarification. I tried 'get_param' yesterday but saw that my curl call was failing to recognize the url with query parameters. Then I  realized this morning that since I am using `zsh` instead of `sh`, I need to enclose my url with quotations so that it gets interpreted as a literal. Without the quotations, `zsh` was expanding the `?` and `=` characters. I just realized that the examples in the [docs](https://falcon.readthedocs.io/en/stable/user/quickstart.html#learning-by-example_) assume that you are using `sh` and thus do not enclose the url with quotations. Either way, lesson learned. Always enclose your url's with quotation marks.
