### ISSUE TITLE
Falcon Test Client throws ValueError when response handler raises HTTPNotFound

### ISSUE THREAD

**Issue by tjb-wiley** [falconry/falcon#1561] opened 2019-07-23 21:50 UTC
I refactored an app to raise `falcon.HTTPNotFound` exception, but now the functional tests fail with a `ValueError: need more than 1 value to unpack` error. I'm using v2.0.0.

In the code below, if I comment out the the line that `raise`'s the exception and just set `resp.media` and `resp.status` manually, the test passes.

I've tried tracking this down using pdb, and ended up digging all the way into the `wsgiref.validate` code, which is triggered from [here](https://github.com/falconry/falcon/blob/master/falcon/testing/client.py#L345) in Falcon's testing client.

Has anyone else experienced this behavior? Or am I just doing something wrong?

I've reproduced this behavior with the following code:
```py
# app.py
import falcon

app = application = falcon.API()


class Resource:

    def on_get(self, req, resp):
        raise falcon.HTTPNotFound('error')
        #resp.media = {'message': 'error'}
        #resp.status = falcon.HTTP_404

app.add_route('/', Resource())
```
And used this test:
```py
#test_app.py
import falcon
from falcon import testing
import pytest

from app import app


@pytest.fixture
def client():
    return testing.TestClient(app)


class TestApp:

    def test_404(self, client):
        response = client.simulate_get('/')
        assert response.status == falcon.HTTP_404
```
I'm using Python 3.7.3 with the following packages installed in a virtualenv:
```pypip freeze
astroid==2.2.5
atomicwrites==1.3.0
attrs==19.1.0
falcon==2.0.0
gunicorn==19.9.0
importlib-metadata==0.18
isort==4.3.21
lazy-object-proxy==1.4.1
mccabe==0.6.1
more-itertools==7.2.0
packaging==19.0
pluggy==0.12.0
py==1.8.0
pylint==2.3.1
pyparsing==2.4.1
pytest==5.0.1
six==1.12.0
typed-ast==1.4.0
wcwidth==0.1.7
wrapt==1.11.2
zipp==0.5.2
```
Here is the actual failure from pytest:
```sh
____________________________________________ TestApp.test_404 ____________________________________________

>   ???

falcon/api.py:269: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <app.Resource object at 0x7f4dbbf52ac8>, req = <Request: GET 'http://falconframework.org/'>
resp = <Response: 404 Not Found>

    def on_get(self, req, resp):
>       raise falcon.HTTPNotFound('error')
E       falcon.errors.HTTPNotFound: error

app.py:9: HTTPNotFound

During handling of the above exception, another exception occurred:

self = <test_app.TestApp object at 0x7f4dbbf74438>
client = <falcon.testing.client.TestClient object at 0x7f4dbbfca208>

    def test_404(self, client):
>       response = client.simulate_get('/')

test_app.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../venvs/falcon-bug/lib/python3.7/site-packages/falcon/testing/client.py:697: in simulate_get
    return self.simulate_request('GET', path, **kwargs)
../../venvs/falcon-bug/lib/python3.7/site-packages/falcon/testing/client.py:764: in simulate_request
    return simulate_request(self.app, *args, **kwargs)
../../venvs/falcon-bug/lib/python3.7/site-packages/falcon/testing/client.py:348: in simulate_request
    iterable = validator(env, srmock)
/usr/lib/python3.7/wsgiref/validate.py:150: in lint_app
    assert_(len(args) == 2, "Two arguments required")
falcon/api.py:273: in falcon.api.API.__call__
    ???
falcon/api.py:775: in falcon.api.API._handle_exception
    ???
falcon/api.py:753: in falcon.api.API._http_error_handler
    ???
falcon/api.py:745: in falcon.api.API._compose_error_response
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   ValueError: need more than 1 value to unpack

falcon/response.py:663: ValueError
```

**Comment by vytas7** [comment] 2019-07-25 17:48
Hi @tjb-wiley , and thanks for the bug report!

Although I can indeed reproduce the issue, I would be inclined to close this as duplicate of https://github.com/falconry/falcon/issues/777 .

The problem is that currently, as opposed to the desired structure laid in https://github.com/falconry/falcon/issues/777, not all HTTP error classes accept parameters in the same fashion. Classes inheriting from `OptionRepresentation` are typical examples of breaking the paradigm. And unfortunately, as you discovered, `HTTPNotFound` falls under that category.

You could fix your issue at hand by using keyword arguments, i.e. specifically choosing what `'error'` is. `title` and `description` could both work. However currently the first parameter is `headers`, which picks your `error`.

**Comment by vytas7** [comment] 2019-07-25 17:53
Duplicates https://github.com/falconry/falcon/issues/777

**Closed by vytas7** 2019-07-25 17:53 UTC
Labels: bug, duplicate

**Comment by tjb-wiley** [comment] 2019-07-26 21:34
@vytas7 thanks for pointing this out. Makes sense and the workaround is good enough for now. :-)
