### ISSUE TITLE
Resources should be able to support multiple hooks.

### ISSUE THREAD

**Issue by alekhrycaiko** [falconry/falcon#1548] opened 2019-05-29 22:07 UTC
We've come across an issue where only a single falcon hook is applied at a given time; overriding previous hooks. It'd be great if resource endpoints supported multiple falcon hooks.

We also noticed that hooks are overriding each other silently. It'd be great if this was a noisier event (for developer convenience).

**Comment by ryanisnan** [comment] 2019-05-29 22:08
:+1:

**Comment by vytas7** [comment] 2019-05-30 08:59
@alekhrycaiko @ryanisnan thanks for the bug report!

Could you provide an isolated example where this is happening? Are you applying hooks to the whole resource class, or its responder methods?

In either case we have quite extensive unit tests for applying multiple hooks, so there must be something non-trivial we missed there.


Thanks in advance!

**Comment by Jithinqw** [comment] 2019-09-03 08:11
I am not able to reproduce issue, I am able to use multiple hooks on the same route.
`@falcon.before(is_token_valid)
    @falcon.before(is_token_in_db)
    @falcon.before(is_user_active)`

**Comment by vytas7** [comment] 2019-11-03 21:30
@alekhrycaiko @ryanisnan I'm closing this hoping you've solved the issue one or another way, but do not hesitate to reopen if this is still a problem!

If you are still experiencing that hooks are overriding each other, could you ideally post the following:
* Your Falcon version
* Your Python version
* If possible, a simple isolated source code example illustrating the issue
* If possible, `pip freeze` of your current environment

@Jithinqw thanks for checking and reporting!

**Closed by vytas7** 2019-11-03 21:30 UTC
Labels: bug, needs-information
