### ISSUE TITLE
Sharing Lock among resources

### ISSUE THREAD

**Issue by CrashLaker** [falconry/falcon#1786] opened 2020-11-22 02:33 UTC
Hi all,

This is my first attempt trying to build an app using falcon so I don't really know If I'm doing it right.
My app consists of 2 routes:
* /recv - receive payload and add to list
* /send - prints and clears the list

I'm using multiprocessing Lock to avoid any concurrencies.
Am I doing it right? I haven't even tried using wsgi yet.

### Problem
The process is hanging after some recvs.
Time 0 - POST
Time 1 - POST
Time 2 - POST
Time 3 - GET to list
Time 4 - POST .... hangs for a while (30secs).. and then returns

the same happens from GET
Time 0 - GET
Time 1 - GET
Time 2 - GET 
Time 4 - POST .... hangs for a while (30secs).. and then returns

### Expected
No delay between calls

Here's my code.
```python
import falcon
import json
from wsgiref import simple_server
from aux import CORSComponent, JSONTranslator
from multiprocessing import Lock

class AlertHistory(object):
    alerts = []
    lock = Lock()
    def push(self, data):
        print("push to get lock")
        with self.lock:
            self.alerts.append(data)
        print("outside push")

    def list(self):
        print("list to get lock")
        with self.lock:
            ret = self.alerts[:]
            self.alerts = []
        print("outside list")
        return ret

class ReceiveAlert(object):
    def __init__(self, hist):
        self.hist = hist
        print("receive init")

    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200
        resp.body = "receive"

    def on_post(self, req, resp):
        resp.status = falcon.HTTP_200
        resp.body = "receive"
        data = req.media
        self.hist.push(req.media)

class SendAlert(object):
    def __init__(self, hist):
        self.hist = hist
        print("sender init")

    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200
        resp.body = json.dumps(self.hist.list())


api = falcon.API(middleware=[
    CORSComponent(),
    #JSONTranslator()
])
# Enable a simple CORS policy for all responses
alert_history = AlertHistory()

receiver = ReceiveAlert(alert_history)
api.add_route('/recv', receiver)

sender = SendAlert(alert_history)
api.add_route('/send', sender)


httpd = simple_server.make_server('0.0.0.0', 12001, api)
httpd.serve_forever()
```

**Comment by vytas7** [comment] 2020-11-22 09:55
Hi @CrashLaker !
I cannot reproduce your issue. I do not have access to your `aux` middleware though, could you also try commenting them out?

Which Python version (simply run `python -V`) are you using? I am not sure about `wsgiref.simple_server`, but I remember similar issues in the possibly related `SimpleHTTPServer` module in Python 2.7.
Just to rule any `wsgiref.simple_server` glitches out, could you also try exactly the same steps with `gunicorn`? Assuming your file is called `test.py`, you could quickly get it going by:
```
pip install gunicorn
gunicorn test:api
```

**Comment by CaselIT** [comment] 2020-11-22 10:49
Also note that using a multiprocessing server, like `gunicorn` will not work with the provided example, since each process will have update and modify it's own version of  `alerts`

**Comment by CrashLaker** [comment] 2020-11-22 11:27
Hi all.

thank you for your reply.
about my env
```
(venv) [root@monitoring src]# uname -a
Linux monitoring 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
(venv) [root@monitoring src]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
(venv) [root@monitoring src]# python3 --version
Python 3.6.8
(venv) [root@monitoring src]# pip freeze
certifi==2020.11.8
chardet==3.0.4
falcon==2.0.0
gunicorn==20.0.4
idna==2.10
requests==2.25.0
urllib3==1.26.2
```
about `gunicorn test:api` it also didn't work.
Strangely this seems not to be working even without the mutex.
```python
class AlertHistory(object):
    alerts = []

    def push(self, data):
        self.alerts.append(data)

    def list(self):
        ret = self.alerts[:]
        self.alerts = []
        return ret
```

The CORS I'm using I just copied from the [example](https://falcon.readthedocs.io/en/stable/user/faq.html#how-do-i-implement-cors-with-falcon).
```python
class CORSComponent(object):
    def process_response(self, req, resp, resource, req_succeeded):
        resp.set_header('Access-Control-Allow-Origin', '*')

        if (req_succeeded
            and req.method == 'OPTIONS'
            and req.get_header('Access-Control-Request-Method')
        ):
            # NOTE(kgriffs): This is a CORS preflight request. Patch the
            #   response accordingly.

            allow = resp.get_header('Allow')
            resp.delete_header('Allow')

            allow_headers = req.get_header(
                'Access-Control-Request-Headers',
                default='*'
            )

            resp.set_headers((
                ('Access-Control-Allow-Methods', allow),
                ('Access-Control-Allow-Headers', allow_headers),
                ('Access-Control-Max-Age', '86400'),  # 24 hours
            ))
```
> Also note that using a multiprocessing server, like gunicorn, will not work with the provided example, since each process will have update and modify it's own version of alerts

Yea @CaselIT i thought it might come to it. As of now 1 process is enough. Maybe later i'll have to offload this logic to another solution.

**Comment by vytas7** [comment] 2020-11-22 12:03
Hi again, 
That sounds odd. Your Linux kernel is very old (more than 7 years), but not sure if this contributes in any way.
Are you able to run Docker? The kernel would be the same under Docker (your kernel), but it would be interesting if you could retest using another userspace, like a recent Ubuntu or Fedora image.

Could you try continuing to peel off layers of complexity, i.e., try arriving at a complete hello world and see if you are still seeing the issue?

Also, could you show the exact command line or script how you are issuing your requests?

**Comment by CrashLaker** [comment] 2020-11-22 12:28
Ok. Just tested on plain Amazon EC2 Linux from scratch.
Got the same behaviour

```bash
$ yum -y install python3 python3-pip
$ python3 -V
Python 3.7.9
$ uname -srpio
Linux 4.14.203-156.332.amzn2.x86_64 x86_64 x86_64 GNU/Linux
$ python3 -m venv .
```

requirements.txt
```
certifi==2020.11.8
chardet==3.0.4
falcon==2.0.0
gunicorn==20.0.4
idna==2.10
requests==2.25.0
urllib3==1.26.2
```

```python
import falcon
import json
from wsgiref import simple_server
from multiprocessing import Lock

class CORSComponent(object):
    def process_response(self, req, resp, resource, req_succeeded):
        resp.set_header('Access-Control-Allow-Origin', '*')

        if (req_succeeded
            and req.method == 'OPTIONS'
            and req.get_header('Access-Control-Request-Method')
        ):
            # NOTE(kgriffs): This is a CORS preflight request. Patch the
            #   response accordingly.

            allow = resp.get_header('Allow')
            resp.delete_header('Allow')

            allow_headers = req.get_header(
                'Access-Control-Request-Headers',
                default='*'
            )

            resp.set_headers((
                ('Access-Control-Allow-Methods', allow),
                ('Access-Control-Allow-Headers', allow_headers),
                ('Access-Control-Max-Age', '86400'),  # 24 hours
            ))

class AlertHistory(object):
    alerts = []
    lock = Lock()
    def push(self, data):
        print("push to get lock")
        with self.lock:
            self.alerts.append(data)
        print("outside push")

    def list(self):
        print("list to get lock")
        with self.lock:
            ret = self.alerts[:]
            self.alerts = []
        print("outside list")
        return ret

class ReceiveAlert(object):
    def __init__(self, hist):
        self.hist = hist
        print("receive init")

    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200
        resp.body = "receive"

    def on_post(self, req, resp):
        resp.status = falcon.HTTP_200
        resp.body = "receive"
        data = req.media
        self.hist.push(req.media)

class SendAlert(object):
    def __init__(self, hist):
        self.hist = hist
        print("sender init")

    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200
        resp.body = json.dumps(self.hist.list())


api = falcon.API(middleware=[
    CORSComponent(),
    #JSONTranslator()
])
# Enable a simple CORS policy for all responses
alert_history = AlertHistory()

receiver = ReceiveAlert(alert_history)
api.add_route('/recv', receiver)

sender = SendAlert(alert_history)
api.add_route('/send', sender)


httpd = simple_server.make_server('0.0.0.0', 80, api)
httpd.serve_forever()
```

**Test for send**
Via browser chrome hit `/send`

**Test for recv**
```python
import requests

url = "<ip>/recv"
data = {"dfasdf": 1}
rs = requests.post(url, json=data)
print(rs.content)
```

**Comment by CrashLaker** [comment] 2020-11-22 12:36
One thing I noticed.
It doesn't hangs and return.
It reaches a timeout:
```
$ gunicorn app:api --bind=0.0.0.0:80
[2020-11-22 12:34:05 +0000] [3645] [CRITICAL] WORKER TIMEOUT (pid:3648)
[2020-11-22 12:34:05 +0000] [3648] [INFO] Worker exiting (pid: 3648)
[2020-11-22 12:34:05 +0000] [3653] [INFO] Booting worker with pid: 3653
```

Also after I start the POST python script which remains hanging.
By the time I refresh the page on the browser the POST request completes

**Comment by vytas7** [comment] 2020-11-22 12:46
Are you sure you have commented out the `wsgiref` part before running `gunicorn` (or made it conditional via `__name__`)?

Could you try the very basic WSGI `test.py` below in your environment (no Falcon involved):
```python
from wsgiref.simple_server import make_server


def api(environ, start_response):
    print('Received request: {REQUEST_METHOD} {PATH_INFO}'.format(**environ))
    status = '200 OK'
    headers = [('Content-type', 'text/plain; charset=utf-8')]
    start_response(status, headers)
    return [b"Just testing"]


if __name__ == '__main__':
    with make_server('', 8000, api) as httpd:
        print("Serving on port 8000...")
        httpd.serve_forever()
```
Run it as `python test.py`, and `gunicorn test:api`, respectively.
Then test against `http://<ip>:8000/whatever`.

**Comment by CrashLaker** [comment] 2020-11-22 13:06
your example works.

i've recorded a part.
3 screens:
left: GET
middle: falcon
right: POST

after running the right window it only continues after I refresh the browser page

![falcon-hang-v2](https://user-images.githubusercontent.com/4432491/99904529-1bf47480-2caa-11eb-883c-5a0dc5121bb3.gif)

**Comment by vytas7** [comment] 2020-11-22 14:04
Thanks for the screencast.

Just to give you a couple of further ideas
* Your code above has a lot of trace `print(...)`s, why don't you run this version on EC2 instead (you were only showing one basic `receive`/`send` instead)?
* Could you add ` --access-logfile -` to your `gunicorn` command line? I.e., `gunicorn --access-logfile - app:api --bind ...`.
* Are you _really_ sure a version without (not even instantiating them) any `multiprocessing` locks still exhibits this behaviour?
* Depending on the above, could you try a `threading.Lock()` instead?

It might also be something either inside your browser, or inside your test loop (how is that run btw?).
Something that establishes the connection to our single-worker server, and pauses it, effectively blocking it from processing any other requests in the meantime. That could be the browser or a browser extension, looking at the screencast. Here is where Gunicorn logging and more trace output might help.
You might even try switching back to `wsgiref`, and dropping into the debugger (`pdb` or any other of your choice).

Hope this helps, cause I simply cannot debug this because I'm not at your machine, nor I have the time to. And I cannot reproduce myself.

You might also want to start a discussion on [our "user" Gitter channel](https://gitter.im/falconry/user), maybe someone else has encountered something similar.

**Comment by CrashLaker** [comment] 2020-11-24 23:56
Somehow this helped me https://github.com/falconry/falcon/issues/998

Starting two workers (or one for each handler) solved my issue idk why

`gunicorn app:api --workers 2`

**Comment by vytas7** [comment] 2020-11-25 08:06
@CrashLaker ,
probably it was something along the lines of:
> Something that establishes a connection to our single-worker server, and pauses it, effectively blocking it from processing any other requests in the meantime. That could be either the browser or a browser extension, looking at the screencast. Here is where Gunicorn logging and more trace output might help.

Note, however, that your `AlertHistory` would diverge to two separate stores upon forking Gunicorn workers, but I assume that's understood.
(Other options include multiple threads, multiple gevent cores if you are using gevent.)

**Comment by vytas7** [comment] 2021-02-21 17:50
Hi again @CrashLaker , I'm going to close this issue since the problem is hopefully understood.
I created another issue to extend our FAQ to mention common causes: https://github.com/falconry/falcon/issues/1868

**Closed by vytas7** 2021-02-21 17:50 UTC
Labels: needs-information, question
