### ISSUE TITLE
Privatize helpers, etc. that really should only be used internally by the framework

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1457] opened 2019-02-22 22:04 UTC
Falcon modules import a number of helper functions that do not begin with an underscore, although such functions are not meant to be part of the public API. Remedy this in the next major version of the framework (as it would be a breaking change).

**Comment by vytas7** [comment] 2019-02-23 14:31
(See also: https://github.com/falconry/falcon/issues/1176 )

**Comment by Vorashil** [comment] 2020-05-20 22:05
Hey, I would like to take this issue if it's still open.

**Comment by vytas7** [comment] 2020-07-01 18:19
Hi @Vorashil !
Yeah, you are very welcome to!
Let us know if you are still interested in working on this though so that we do not duplicate efforts.

**Comment by Vorashil** [comment] 2020-07-01 22:04
Hi @vytas7 . Yes, I am still keen to do it. Please assign it to me. Thanks in advance.

**Comment by vytas7** [comment] 2020-07-02 12:18
We don't assign in any particular way :slightly_smiling_face: Your confirmation here is enough.
Looking forward to your PR!

**Comment by bradleydamato** [comment] 2020-10-02 15:37
@vytas7 @kgriffs do the helper functions include those shown here? https://github.com/falconry/falcon/blob/105c56db6a727da7231512c43fd4974a53fc960c/falcon/util/sync.py

If so, I'd like to fix these specifically.

**Comment by vytas7** [comment] 2020-10-02 16:52
Hi @bradleydamato !
Do you have any specific function from `sync.py` in mind? Most of these functions are meant to be available as utilites in the public API by design: https://falcon.readthedocs.io/en/latest/api/util.html#async . Furthermore, all this sync-async stuff is not a part of any stable release, as it was introduced only as part of the 3.0.0 release cycle, and we are, at the time of writing, at 3.0.0a2; so we can still make adjustments semi-freely.

As I understand this issue is mostly about functions that are already "public" (i.e., not prefixed with an underscore) in Falcon 2.0, but are not documented, and not meant to be a part of the public API.
I would let @kgriffs confirm, but IMHO `falcon.app_helpers.prepare_middleware` could serve as an illustration. Despite having a decent docstring, it does look to be deeply tied to internal interfaces and implementation details (returning a tuple of three tuples of methods :) ).

**Comment by abid1998** [comment] 2021-06-28 18:24
Hello I can take this up. What exactly needs to be done here?

**Comment by vytas7** [comment] 2024-08-26 09:23
Typing PRs such as #2271 introduced new constants like `MISSING` that may be used at runtime without underscore in some places.

These also need to be privatized.

**Comment by vytas7** [comment] 2024-09-26 14:07
I took a stab at this, and proposed a PR privatizing some request and reponse helpers.
If we want to privatize even more stuff, let us file a new issue, either for 4.x (privatize with a deprecation note), or 5.0 (privatize with or without deprecation notes).

**Closed** 2024-09-26 17:56 UTC
Labels: cleanup, breaking-change, falcon-4.0::beta
