### ISSUE TITLE
Request object uri/url property returns wrong value

### ISSUE THREAD

**Issue by pressyfdo** [falconry/falcon#852] opened 2016-07-27 15:27 UTC
When I send request to the uri/url `http://127.0.0.1/app/url`, the value returned by `req.uri/req.url` is `http://127.0.0.1/app/app/url` yet the application works perfectly. 
When I look into the falcon's `request.py` file, it looks like the value of the `req.uri` is wrongly formatted.

I have posted the part where i guess it might had gone wrong below:

File: `request.py` - Line numbers 490, 491, 492, and 493.

`value = (protocol + '://' +
                     host +
                     self.app +
                     self.path)`

In my senario,
value of `protocol` is `http`
value of `host` is `127.0.0.1`,
value of `self.app` is `/app`,
value of `self.path` is `/app/url`

so the returned value is `http://127.0.0.1/app/app/url`.

Kindly have a look into this issue. Thank you.

**Comment by kgriffs** [comment] 2017-04-25 18:40
Hi @pressyfdo, what web server are you using to host this app? Can you share your configuration? `Request.app` simply returns the `SCRIPT_NAME` WSGI environment variable, which is controlled by the server configuration. It looks like the server is including the base portion of the path (`app`) in both the `SCRIPT_NAME` and `PATH_INFO` WSGI variables, contrary to the WSGI specification.

You can see exactly what the server is passing in the environment by mounting this application instead of the falcon app:

```py
def application(environ, start_response):

    start_response('200 OK', [
        ('Content-Type', 'text/plain')])

    body = '\n{\n'
    for key, value in environ.items():
        body += '    "{0}": "{1}",\n'.format(key, value)

    body += '}\n\n'

    if not isinstance(body, bytes):
        body = body.encode('utf-8')

    return [body]
```

**Comment by pressyfdo** [comment] 2017-05-09 06:54
I use `gunicorn` application server to host this application.

For the url `http://127.0.0.1/app/url`,

The output after executing the above code is,

```
{
    "HTTP_USER_AGENT": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36",
    "wsgi.input": "<gunicorn.http.body.Body object at 0x7f20a2c3d780>",
    "HTTP_COOKIE": "session=.eJwljktqAzEQRK8iem2Cfq3PnCL7YEKru-UZmMRmNF4Z3z2CrIqiHsV7wXffaaw6YPl6gTlnwI-OQTeFC3zuSkPNfr-Z7decd0PMczTnug3zmMwHXN_Xyzw5dKywnMdTZ9sEFvBOrQ-tR0xoWVJHZazNS8GaxBKyJ-dD7OwaSWi5lUKSo4-liNRE6DUVdqwaLLfaQpbSQ2wS1NpkM_uAKSqlTGJt7SUS2oitcO1Tc-o_hx7_Mg7ef9DsRp0.C-07qg.yguSWaLLtzne2_SLswVk4hzNE4M",
    "HTTP_HOST": "localhost:5000",
    "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.8",
    "HTTP_CONNECTION": "keep-alive",
    "wsgi.multiprocess": "False",
    "gunicorn.socket": "<socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('127.0.0.1', 49268)>",
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "QUERY_STRING": "",
    "wsgi.multithread": "False",
    "wsgi.run_once": "False",
    "SERVER_PORT": "5000",
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1",
    "REMOTE_PORT": "49268",
    "SERVER_PROTOCOL": "HTTP/1.1",
    "wsgi.errors": "<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f20a2c3d748>",
    "wsgi.url_scheme": "http",
    "wsgi.version": "(1, 0)",
    "wsgi.file_wrapper": "<class 'gunicorn.http.wsgi.FileWrapper'>",
    "PATH_INFO": "/app/url
    "REMOTE_ADDR": "127.0.0.1",
    "SCRIPT_NAME": "",
    "SERVER_NAME": "0.0.0.0",
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, sdch",
    "REQUEST_METHOD": "GET",
    "RAW_URI": "/app/url",
    "SERVER_SOFTWARE": "gunicorn/19.6.0",
}
```

and for the `falcon` app with `gunicorn`, the value of `req.env` is,

```
{
 'wsgi.multithread': False,
 'wsgi.url_scheme': 'http', 
'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'HTTP_ACCEPT':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 
'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 
'beaker.get_session': <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x7f732c7914a8>>, 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8', 
'REMOTE_PORT': '50990', 
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch', 
'beaker.session': {'_accessed_time': 1494282989.2567835, '_creation_time': 1494282989.2567835}, 
'wsgi.multiprocess': False,
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f732c7a45f8>, 
'RAW_URI': '/app/url',
 'SERVER_NAME': '0.0.0.0', 
'HTTP_COOKIE': 'session=.eJwljktqAzEQRK8iem2Cfq3PnCL7YEKru-UZmMRmNF4Z3z2CrIqiHsV7wXffaaw6YPl6gTlnwI-OQTeFC3zuSkPNfr-Z7decd0PMczTnug3zmMwHXN_Xyzw5dKywnMdTZ9sEFvBOrQ-tR0xoWVJHZazNS8GaxBKyJ-dD7OwaSWi5lUKSo4-liNRE6DUVdqwaLLfaQpbSQ2wS1NpkM_uAKSqlTGJt7SUS2oitcO1Tc-o_hx7_Mg7ef9DsRp0.C-07qg.yguSWaLLtzne2_SLswVk4hzNE4M', 
'HTTP_CACHE_CONTROL': 'max-age=0',
'PATH_INFO': '/app/url',
 'wsgi.run_once': False, 
'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36', 
'SCRIPT_NAME': '/app',
 'QUERY_STRING': '', 
'HTTP_CONNECTION': 'keep-alive',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'HTTP_HOST': 'localhost:5000',
 'SERVER_SOFTWARE': 'gunicorn/19.6.0', 'wsgi.version': (1, 0),
 'wsgi.input': <gunicorn.http.body.Body object at 0x7f732c7a4cf8>, 
'REMOTE_ADDR': '127.0.0.1', 
'REQUEST_METHOD': 'GET', 
'SERVER_PORT': '5000', 
'gunicorn.socket': <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('127.0.0.1', 50990)>
}
```

**Comment by vytas7** [comment] 2019-11-03 21:06
Hi @pressyfdo ,
Looking at this 2 years later, I cannot really reproduce it with Gunicorn 19.9.0.

The only way I could cram something into `SCRIPT_NAME` was using the envvar `SCRIPT_NAME=/app` specifically for that purpose, but then still everything worked as expected:

```json
{
    "HTTP_ACCEPT": "*/*",
    "HTTP_ACCEPT_ENCODING": "gzip, deflate",
    "HTTP_CONNECTION": "keep-alive",
    "HTTP_HOST": "127.0.0.1:8000",
    "HTTP_USER_AGENT": "HTTPie/1.0.2",
    "PATH_INFO": "/app/url",
    "QUERY_STRING": "",
    "RAW_URI": "/app/app/url",
    "REMOTE_ADDR": "127.0.0.1",
    "REMOTE_PORT": "38702",
    "REQUEST_METHOD": "GET",
    "SCRIPT_NAME": "/app",
    "SERVER_NAME": "127.0.0.1",
    "SERVER_PORT": "8000",
    "SERVER_PROTOCOL": "HTTP/1.1",
    "SERVER_SOFTWARE": "gunicorn/19.9.0",
    "gunicorn.socket": "<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 38702)>",
    "wsgi.errors": "<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f1091a17128>",
    "wsgi.file_wrapper": "<class 'gunicorn.http.wsgi.FileWrapper'>",
    "wsgi.input": "<gunicorn.http.body.Body object at 0x7f1091a173c8>",
    "wsgi.multiprocess": "False",
    "wsgi.multithread": "False",
    "wsgi.run_once": "False",
    "wsgi.url_scheme": "http",
    "wsgi.version": "(1, 0)"
}
```

Closing this, but do not hesitate to reopen if you are still seeing this with Falcon+recent Gunicorn.

Test program I used:
```python
import falcon


class Debug:
    def on_get(self, req, resp):
        resp.media = {key: str(value) for key, value in req.env.items()}


app = falcon.API()
app.add_route('/app/url', Debug())
```

**Closed by vytas7** 2019-11-03 21:06 UTC
Labels: needs-information
